{{- if .Values.kafkaUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kafkaUi.replicaCount }}
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.kafkaUi.kafkaBrokers | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.kafkaUi.service.type }}
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: {{ .Values.kafkaUi.service.port }}
      targetPort: 8080
{{- end }}