apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    DB_PASSWORD: AgC8Qf7/2uBSqgG49ysjMBNKvgrnDzTfdNmkpfnTQ6PSmv/2cwl7gm1V8JByWoDGMtyvd629xi6WdZAXSL9SyD0GCUH/lkOznX7Lc/5rqE6CMHQScvlyyj1Nnckw72etwb3pkqVmOYrS0ty3+OIPbZaJxAWbBJeAWX6AkrDJb35SyuCYB80Vc0iRp2ZTlQo8gSuxWr5/GghfdSQQLWE995C/dqCmZwv72i8HPzzEAHln3skxY+HeNLTFWuwVAK1JaTcq8jDF+MgJfaf4DDfBAcKve5A7jUtbBOoTu6/veatRL32GHlEgIF0kk2K4o5P1p246ESG4xNdB45k/yzcMX69hMLFyZsZtVcENhRz0W3swGfs0/4W42uNMZoeAxuALcaBVqoYvlT+V9eemFSfTPuWEZgenp/gO+AWQOkAucbhXjsnB5h0JGPbNnAfDgUT55tbLIPw/sKyIgbsDswwwbjbw8mLScoeGsHAxcsTzcN86KzI4cEkw6T9kZspCBzQoUxjKR9BdswubbkCpJo5BmcD79lYwE83dVQvGfb/MCmmUgkmR13qJJjznp51ngriE71dOpolGeoSw5wqACIGoh7dJjJ5vTFKY7B87kuwUmoZVPh30r2Bz6UnJdrUMQb5davYpMe4qOorDBfwUIdeYPXQXxQaVVd090a/QzpMg7kJXMdyNbyghPgFvR5GS4I7kolvfVqti
  template:
    metadata:
      name: postgres-secret
      namespace: {{ .Release.Namespace }}