apiVersion: v2
name: portfolio-app
description: A Helm chart for Raju's Fullstack Portfolio
type: application

# Ye chart ka version hai (jab aap chart ka structure badlein tab badlein)
version: 0.1.0

# Ye aapke app ka version hai
appVersion: "1.0.0"