FROM debezium/connect:2.5

USER root
RUN curl -L --output /tmp/elasticsearch-connector.zip \
    https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/14.0.15/kafka-connect-elasticsearch-14.0.15.zip \
    && unzip /tmp/elasticsearch-connector.zip -d /kafka/connect/ \
    && rm -f /tmp/elasticsearch-connector.zip

USER kafka