apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./portfolio/k8s
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  # Ye section ensure karta hai ki values.yaml se data uthaya jaye
  valuesFrom:
    - kind: ConfigMap
      name: portfolio-values
      optional: true