apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio
  namespace: raju
spec:
  interval: 1m
  releaseName: portfolio
  chart:
    spec:
      chart: ./charts/portfolio
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    globalTag: "v26.100.9"
    imagePullSecrets:
      - regcred
    backend:
      replicaCount: 2
      image:
        repository: 2024dock/portfolio-backend
        pullPolicy: Always
      service:
        type: ClusterIP
        port: 5000
      config:
        DB_HOST: "192.168.49.1"
        DB_USER: "postgres"
        DB_NAME: "portfolio"
        DB_PORT: "5432"
    frontend:
      replicaCount: 1
      image:
        repository: 2024dock/portfolio-frontend
        pullPolicy: Always
      service:
        type: ClusterIP
        port: 80
    ingress:
      enabled: true
      className: nginx
      host: raju.local
      tls:
        enabled: true
        secretName: portfolio-tls
